{
	"version": 1598897695,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/unknown-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite16-sheet0.png",
		"images/sceleton_topor-sheet0.png",
		"images/sceleton_topor-sheet1.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite19-sheet1.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/imgonlinecomuagifanimationbjnbppy7wis-sheet0.png",
		"images/imgonlinecomuagifanimationbjnbppy7wis-sheet1.png",
		"images/imgonlinecomuagifanimationbjnbppy7wis-sheet2.png",
		"images/sprite27-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite29-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite32-sheet0.png",
		"images/key-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/jump_boost-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite36-sheet1.png",
		"images/sprite37-sheet0.png",
		"images/sprite38-sheet0.png",
		"images/sprite39-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite40-sheet1.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/armor-sheet0.png",
		"images/sprite43-sheet0.png",
		"images/sprite46-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/crystal_ug-sheet0.png",
		"images/crystal_ug_sm-sheet0.png",
		"images/rock_ark-sheet0.png",
		"images/cave-sheet0.png",
		"images/ug_road_up-sheet0.png",
		"images/ug_road-sheet0.png",
		"images/ug_bridge-sheet0.png",
		"images/Безимени-sheet0.png",
		"images/stalagmite-sheet0.png",
		"images/crystal_ug_big-sheet0.png",
		"images/crystal_ug_big2-sheet0.png",
		"images/Безимени2-sheet0.png",
		"images/sprite48-sheet0.png",
		"images/sprite49-sheet0.png",
		"images/inf_road-sheet0.png",
		"images/inf_road2-sheet0.png",
		"images/inf_road3-sheet0.png",
		"images/lava_hill-sheet0.png",
		"images/inf_rock-sheet0.png",
		"images/inf_skool-sheet0.png",
		"images/inf_tower-sheet0.png",
		"images/inf_tower_dark-sheet0.png",
		"images/inf_dange-sheet0.png",
		"images/sprite50-sheet0.png",
		"images/sprite50-sheet1.png",
		"images/sprite50-sheet2.png",
		"images/animal-sheet0.png",
		"images/cr1s-sheet0.png",
		"images/vilager-sheet0.png",
		"images/vilager-sheet1.png",
		"images/sprite52-sheet0.png",
		"images/sprite54-sheet0.png",
		"images/r-sheet0.png",
		"images/villager_say-sheet0.png",
		"images/villager_hut-sheet0.png",
		"images/villager_red-sheet0.png",
		"images/villager_red_say-sheet0.png",
		"images/village_hut_g-sheet0.png",
		"images/knight_tower-sheet0.png",
		"images/wall_villagers-sheet0.png",
		"images/wall_villagers_back-sheet0.png",
		"images/knight_say-sheet0.png",
		"images/knight_say2-sheet0.png",
		"images/knight_say3-sheet0.png",
		"images/wood-sheet0.png",
		"images/rock-sheet0.png",
		"images/e-sheet0.png",
		"images/knight-sheet0.png",
		"images/knight-sheet1.png",
		"images/grass-sheet0.png",
		"images/sprite55-sheet0.png",
		"images/sprite57-sheet0.png",
		"images/sprite57-sheet1.png",
		"images/fl-sheet0.png",
		"images/gold-sheet0.png",
		"images/gold2-sheet0.png",
		"images/trade_arrow-sheet0.png",
		"images/bridge-sheet0.png",
		"images/vilager_m-sheet0.png",
		"images/sprite59-sheet0.png",
		"images/perehod-sheet0.png",
		"images/bereza-sheet0.png",
		"images/oak-sheet0.png",
		"images/elf_terrian-sheet0.png",
		"images/ant-sheet0.png",
		"images/elf_wood-sheet0.png",
		"images/tree_elf-sheet0.png",
		"images/particles.png",
		"images/sprite60-sheet0.png",
		"images/blood-sheet0.png",
		"images/blood2-sheet0.png",
		"images/sprite61-sheet0.png",
		"images/elf_tree-sheet0.png",
		"images/grass2-sheet0.png",
		"images/machroom-sheet0.png",
		"images/sprite62-sheet0.png",
		"images/sprite62-sheet1.png",
		"images/sprite62-sheet2.png",
		"images/tower_elf-sheet0.png",
		"images/elf_tower-sheet0.png",
		"images/elf_tower2-sheet0.png",
		"images/sprite63-sheet0.png",
		"images/sprite63-sheet1.png",
		"images/vilager_green-sheet0.png",
		"images/vilager_green-sheet1.png",
		"images/unknown2-sheet0.png",
		"images/d6fip-sheet0.png",
		"images/bg-sheet0.png",
		"images/bg2-sheet0.png",
		"images/иппп-sheet0.png",
		"images/suva-sheet0.png",
		"images/tiledbackground2.png",
		"images/hero_-sheet0.png",
		"images/wzxp33nr-sheet0.png",
		"images/crystal__-sheet0.png",
		"images/crystal__2-sheet0.png",
		"images/bgw-sheet0.png",
		"images/bgw2-sheet0.png",
		"images/men_res-sheet0.png",
		"images/men_res2-sheet0.png",
		"images/rock_res-sheet0.png",
		"images/magic_book_menu-sheet0.png",
		"images/fire-sheet0.png",
		"images/poison-sheet0.png",
		"images/purple_death-sheet0.png",
		"images/terran_ung-sheet0.png",
		"media/door-lock-3_zkwogmvd (online-audio-converter.com).m4a",
		"media/door-lock-3_zkwogmvd (online-audio-converter.com).ogg",
		"media/03844 (online-audio-converter.com).m4a",
		"media/03844 (online-audio-converter.com).ogg",
		"media/your_file_(tools.diktorov.net) (2).m4a",
		"media/your_file_(tools.diktorov.net) (2).ogg",
		"media/your_file_(tools.diktorov.net) (3).m4a",
		"media/your_file_(tools.diktorov.net) (3).ogg",
		"media/10571 (online-audio-converter.com).m4a",
		"media/10571 (online-audio-converter.com).ogg",
		"media/10 - terrain - grass (online-audio-converter.com).m4a",
		"media/10 - terrain - grass (online-audio-converter.com).ogg",
		"media/11 - terrain - lava (online-audio-converter.com).m4a",
		"media/11 - terrain - lava (online-audio-converter.com).ogg",
		"media/vspyshka-plameni_[pro-sound.org].m4a",
		"media/vspyshka-plameni_[pro-sound.org].ogg",
		"media/3168cb267b71c4d (online-audio-converter.com).m4a",
		"media/3168cb267b71c4d (online-audio-converter.com).ogg",
		"media/supernova-whoosh_fyoldh4o (online-audio-converter.com).m4a",
		"media/supernova-whoosh_fyoldh4o (online-audio-converter.com).ogg",
		"media/322191dc7c6ad15.m4a",
		"media/322191dc7c6ad15.ogg",
		"media/acid_burn_010_14878.m4a",
		"media/acid_burn_010_14878.ogg",
		"media/00923.m4a",
		"media/00923.ogg",
		"media/zvuk-atakujuschej-zmei.m4a",
		"media/zvuk-atakujuschej-zmei.ogg",
		"media/1549458529_cobra-striking_f1sfkpnu1.m4a",
		"media/1549458529_cobra-striking_f1sfkpnu1.ogg",
		"media/e46047c3280f091.m4a",
		"media/e46047c3280f091.ogg",
		"media/15 - terrain - underground.m4a",
		"media/15 - terrain - underground.ogg",
		"media/93006fc5ce5bae4.m4a",
		"media/93006fc5ce5bae4.ogg",
		"media/tribes of the east - 01 - main menu (online-audio-converter.com).m4a",
		"media/tribes of the east - 01 - main menu (online-audio-converter.com).ogg",
		"media/02 - credits (online-audio-converter.com).m4a",
		"media/02 - credits (online-audio-converter.com).ogg",
		"media/01460 (online-audio-converter.com).m4a",
		"media/01460 (online-audio-converter.com).ogg",
		"media/12 - terrain - rough (online-audio-converter.com).m4a",
		"media/12 - terrain - rough (online-audio-converter.com).ogg",
		"media/8dd4dad4b24042d (online-audio-converter.com).m4a",
		"media/8dd4dad4b24042d (online-audio-converter.com).ogg",
		"media/monsters-breath_g1bqzbeu (online-audio-converter.com).m4a",
		"media/monsters-breath_g1bqzbeu (online-audio-converter.com).ogg",
		"media/bloody-nightmare-breaths_14 (online-audio-converter.com).m4a",
		"media/bloody-nightmare-breaths_14 (online-audio-converter.com).ogg",
		"media/witch-killer-hit_fyc_gbed (online-audio-converter.com).m4a",
		"media/witch-killer-hit_fyc_gbed (online-audio-converter.com).ogg"
	]
}